import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RxHamburgerMenu } from "react-icons/rx";
import { IoSearchOutline } from "react-icons/io5";
import { IoCartOutline } from "react-icons/io5";
import { IoPersonCircleOutline } from "react-icons/io5";
import Link from "next/link";
import Footer from "./products/components/Footer"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Microsoft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-evenly items-center border-b px-3 h-[70px] bg-white">
          <div className="flex justify-between items-center">
          <Link href="/"><img className="mr-[20px] hidden md:block w-[130px]" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/1280px-Microsoft_logo_%282012%29.svg.png" alt="" /></Link>
          <div className="hidden md:block">
              <ul className="flex gap-6 items-center">
              <li></li>
              <li><Link href="/products">products</Link></li>
              <li><Link href="">Copilot</Link></li>
              <li><Link href="">Windows</Link></li>
              <li><Link href="">Surface</Link></li>
              <li><Link href="">Xbox</Link></li>
              <li><Link href="">Support</Link></li>
            </ul>
          </div>
         </div>
          <div className="lg:flex gap-6 hidden lg:block items-center">
            <div>All Microsoft</div>
            <div className="flex items-center gap-1">Search<IoSearchOutline className="text-[22px]"/></div>
            <div className="flex items-center gap-1">Cart<IoCartOutline className="text-[22px]"/></div>
            <div className="flex items-center gap-1">Santosh<IoPersonCircleOutline className="text-[30px]"/></div>
          </div>
          <div className="sm:block md:hidden text-[26px]"><RxHamburgerMenu /></div>
          <div className="sm:block md:hidden text-[26px]"><IoSearchOutline /></div>
          <div><img className="sm:block md:hidden w-[130px]" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/1280px-Microsoft_logo_%282012%29.svg.png" alt="" /></div>
          <div className="sm:block md:hidden text-[26px]"><IoCartOutline />
          </div>
          <div className="sm:block md:hidden text-[26px]"><IoPersonCircleOutline /></div>
        </header>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
